export const theme = {
  colors: {
    primary: '#6C5CE7',
    secondary: '#00CAF2',
    accent: '#FF2E63',
    background: '#1A1A2E',
    surface: '#232342',
    text: '#FFFFFF',
    textSecondary: '#A0A0B9',
    success: '#00B894',
    warning: '#FFB800',
    error: '#FF4757',
    neonBlue: '#18E6F7',
    neonPink: '#FF2E63',
    neonPurple: '#B668FF',
    glassBg: 'rgba(255, 255, 255, 0.1)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  shadows: {
    soft: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};
